name: Build ISO

on:
 workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
   
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt -y install build-essential mtools xorriso grub-common squashfs-tools
    
    - name: build
      run: ./fetch_build
      
